CREATE TABLE chicken(
    id BIGSERIAL PRIMARY KEY,
    weight SMALLINT NOT NULL,
    birth_date DATE NOT NULL,
    breed_id BIGINT NOT NULL REFERENCES breed(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE breed
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();