spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kurkod_service}
    username: ${DB_USER:kurkod_service_user}
    password: ${DB_PASSWORD:kurkod_service_password}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    try-it-out-enabled: true

logging:
  level:
    io.github.artsobol: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
