spring:
  application:
    name: kurkod-service

  profiles:
    default: dev

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: list
    display-request-duration: true

server:
  port: ${SERVER_PORT:8189}

swagger:
  servers:
    first: ${SWAGGER_SERVER:http://localhost:${server.port}}

app:
  security:
    jwt:
      base64-signing-key: ${JWT_SECRET}
      access-token-lifetime: ${JWT_LIFETIME:PT1H}
  i18n:
    basename: classpath:i18n/messages/messages,classpath:i18n/errors/errors,classpath:i18n/validations/validations
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-seconds: 0
